# Generated by Django 5.0.1 on 2024-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlistings",
            name="bid_counter",
        ),
        migrations.RemoveField(
            model_name="auctionlistings",
            name="winner",
        ),
        migrations.AlterField(
            model_name="auctionlistings",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
