# Generated by Django 5.0.1 on 2024-02-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_remove_auctionlistings_bid_counter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlistings",
            name="winner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
