# Generated by Django 5.0.1 on 2024-02-09 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_auctionlistings_winner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name": "comment", "verbose_name_plural": "comments"},
        ),
        migrations.RenameField(
            model_name="auctionlistings",
            old_name="created_at",
            new_name="datetime",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="created_at",
            new_name="datetime",
        ),
        migrations.AlterField(
            model_name="auctionlistings",
            name="imageURL",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auctions.auctionlistings",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "watchlist",
                "verbose_name_plural": "watchlists",
                "unique_together": {("auction", "user")},
            },
        ),
    ]
