# Generated by Django 5.0.1 on 2024-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_auctionlistings_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlistings",
            name="winner",
        ),
    ]
